services:
  auth:
    image:
      repository: avernusx/otus4-auth
      tag: "0.1"
    replicaCount: 1
    deployment:
      port: 5000
    service:
      port: 5000
  users:
    image:
      repository: avernusx/otus4-users
      tag: "0.1"
    replicaCount: 1
    deployment:
      port: 5000
    service:
      port: 5000
  
postgresql:
  enabled: true
  postgresqlUsername: dev
  postgresqlPassword: dev
  postgresqlDatabase: dev
  service:
    port: 5432
  initdbUser: "postgres"
  initdbScripts:
    db-init.sql: |
      CREATE EXTENSION if not exists pgcrypto;  

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp"] 

ingressName: nginx-nginx-ingress-controller      