apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    {{- include "app.labels" . | nindent 4 }}
    deployment: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.services.auth.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      deployment: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        deployment: {{ .Release.Name }}-auth
    spec:
      containers:
        - image: "{{ .Values.services.auth.image.repository }}:{{ .Values.services.auth.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.services.auth.deployment.port }}
              name: http
          env:
            - name: DB_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DB_PASS
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DB_HOST
              value: {{ include "postgresql.fullname" . }}
            - name: DB_PORT
              value: {{ .Values.postgresql.service.port | quote }}
          livenessProbe:
            httpGet:
              port: {{ .Values.services.auth.deployment.port }}
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{ .Values.services.auth.deployment.port }}
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-auth
spec:
  ports:
    - port: {{ .Values.services.auth.service.port }}
      name: web
      protocol: TCP
      targetPort: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    deployment: {{ .Release.Name }}-auth
  type: NodePort