apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nonauthorized-ingress
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-users
          servicePort: 5000
        path: /create
      - backend:
          serviceName: {{ .Release.Name }}-auth
          servicePort: 5000
        path: /signin
      - backend:
          serviceName: {{ .Release.Name }}-auth
          servicePort: 5000
        path: /signout
      - backend:
          serviceName: {{ .Release.Name }}-auth
          servicePort: 5000
        path: /auth
      - backend:
          serviceName: {{ .Release.Name }}-auth
          servicePort: 5000
        path: /not-authorized
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authorized-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Release.Name }}-auth.default.svc.cluster.local:5000/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/not-authorized"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id"
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-users
          servicePort: 5000
        path: /me
      - backend:
          serviceName: {{ .Release.Name }}-users
          servicePort: 5000
        path: /update
      - backend:
          serviceName: {{ .Release.Name }}-users
          servicePort: 5000
        path: /health